<?php

namespace AppBundle\Repository;

/**
 * CartonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartonRepository extends \Doctrine\ORM\EntityRepository
{
}
