<?php

namespace AppBundle\Repository;

/**
 * DocumentLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
