<?php

namespace AppBundle\Repository;

/**
 * PickerLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PickerLogRepository extends \Doctrine\ORM\EntityRepository
{
}
