<?php

namespace AppBundle\Repository;

/**
 * ProductDimensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDimensionRepository extends \Doctrine\ORM\EntityRepository
{
}
