app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
erp_api:
    resource: "@WilliamsErpBundle/Resources/config/routes.yml"
    prefix: /api
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"