app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logicbroker:
    resource: "@LogicBrokerBundle/Controller/"
    type:     annotation
    prefix: /logicbroker

dsco:
    resource: "@DscoBundle/Controller/"
    type:     annotation
    prefix: /dsco
    
erp_api:
    resource: "@ErpBundle/Resources/config/routes.yml"
    prefix: /api
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"