# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
        
    app.mfg_erp.service:
        class: Williams\ErpBundle\Service\ErpServerService
        arguments: [ "%erp_server%", "%erp_username%", "%erp_password%", "MFG", "wms-server-mfg" ] 
                
    app.product_service:
        class: AppBundle\Service\ProductService
        arguments: [ "@williams_erp.service", "@williams_wholesale.service" ]
        
    app.connectship_service:
        class: Williams\ConnectshipBundle\Service\ConnectshipService
        arguments: [ "%connectship_api_wsdl%" ]
        
    app.williams_wms:
        class: Williams\WmsBundle\Service\WmsService
        arguments: [ "%williams_wsdl_url%", "%williams_username%", "%williams_password%" ] 
        
    app.muffs_wms:
        class: Williams\WmsBundle\Service\WmsService
        arguments: [ "%muffs_wsdl_url%", "%muffs_username%", "%muffs_password%" ] 
        
    app.order_service:
        class: AppBundle\Service\OrderService
        arguments: [ "@williams_erp.service", "@app.connectship_service", "@app.muffs_wms", "@app.williams_wms", "@doctrine.orm.entity_manager" ]
        
    app.mfg_order_service:
        class: AppBundle\Service\OrderService
        arguments: [ "@app.mfg_erp.service", "@app.connectship_service", "@app.muffs_wms", "@app.williams_wms", "@doctrine.orm.entity_manager" ]
        
    app.reports:
        class: AppBundle\Service\ReportService
        arguments: [ "@app.order_service", "@app.product_service" ]